fx_version 'cerulean'
game 'gta5'
lua54 'yes'
author 'Nevairi | VoltLabs'
description 'Simple car washing script for QBCore'
version '1.0.0'

shared_script 'config.lua'
client_script 'client.lua'
server_script 'server.lua'
